<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13309" started-at="2019-08-16T04:31:14Z" finished-at="2019-08-16T04:31:28Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13309" started-at="2019-08-16T04:31:14Z" finished-at="2019-08-16T04:31:28Z">
      <class name="qsp.Test_Login">
        <test-method status="PASS" signature="openAppln()[pri:0, instance:qsp.Test_Login@5f150435]" name="openAppln" is-config="true" duration-ms="6578" started-at="2019-08-16T10:01:14Z" finished-at="2019-08-16T10:01:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAppln -->
        <test-method status="FAIL" signature="testLogin()[pri:0, instance:qsp.Test_Login@5f150435]" name="testLogin" duration-ms="1247" started-at="2019-08-16T10:01:21Z" finished-at="2019-08-16T10:01:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [actiTIME - Enter Time-Track123] but found [actiTIME - Enter Time-Track]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [actiTIME - Enter Time-Track123] but found [actiTIME - Enter Time-Track]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at qsp.Test_Login.testLogin(Test_Login.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="closeAppln()[pri:0, instance:qsp.Test_Login@5f150435]" name="closeAppln" is-config="true" duration-ms="5466" started-at="2019-08-16T10:01:22Z" finished-at="2019-08-16T10:01:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeAppln -->
      </class> <!-- qsp.Test_Login -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
